# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Celeborn CI

on:
  push:
    branches:
      - main
      - branch-*
      - develop/**
  pull_request:
    branches:
      - main
      - branch-*
      - develop/**

jobs:
  service:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: maven
        check-latest: false
        server-id: arenadata
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
    - name: Test Service with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
      run: build/mvn -Pgoogle-mirror -Pjdk-${{ matrix.java }} -Dscalatest.rerunFailingTestsCount=2 -Dsurefire.rerunFailingTestsCount=2 -fae test
    - name: Upload test log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: service-java-${{ matrix.java }}-unit-test-log
        path: |
          **/target/test-reports/**
          **/target/unit-tests.log

    - name: Upload coverage to Codecov
      if: matrix.java == 8
      uses: codecov/codecov-action@v3

  spark3:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
        spark:
          - '3.5'
        shuffle-plugin-class:
          - 'org.apache.spark.shuffle.sort.io.LocalDiskShuffleDataIO'
          - 'org.apache.spark.shuffle.celeborn.CelebornShuffleDataIO'
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: maven
        check-latest: false
        server-id: arenadata
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
    - name: Test with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
      run: |
        SPARK_BINARY_VERSION=${{ matrix.spark }}
        SPARK_MAJOR_VERSION=${SPARK_BINARY_VERSION%%.*}
        # enable AWS profile to run end-to-end tests with S3 storage
        PROFILES="-Pgoogle-mirror,aws,spark-${{ matrix.spark }},jdk-${{ matrix.java }}"
        TEST_MODULES="client-spark/common,client-spark/spark-${SPARK_MAJOR_VERSION},client-spark/spark-${SPARK_MAJOR_VERSION}-columnar-common,client-spark/spark-${SPARK_MAJOR_VERSION}-shaded,tests/spark-it"
        build/mvn $PROFILES -pl $TEST_MODULES -am clean install -DskipTests
        build/mvn $PROFILES -pl $TEST_MODULES -Dscalatest.rerunFailingTestsCount=2 -Dsurefire.rerunFailingTestsCount=2 -fae -Dspark.shuffle.sort.io.plugin.class=${{ matrix.shuffle-plugin-class }} test
    - name: Upload test log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: spark-${{ matrix.spark }}-java-${{ matrix.java }}-unit-test-log
        path: |
          **/target/test-reports/**
          **/target/unit-tests.log

  spark4:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
        spark:
          - '4.2'
        shuffle-plugin-class:
          - 'org.apache.spark.shuffle.celeborn.CelebornShuffleDataIO'
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven
          check-latest: false
          server-id: arenadata
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Test with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
        run: |
          SPARK_BINARY_VERSION=${{ matrix.spark }}
          SPARK_MAJOR_VERSION=${SPARK_BINARY_VERSION%%.*}
          # enable AWS profile to run end-to-end tests with S3 storage
          PROFILES="-Pgoogle-mirror,aws,spark-${{ matrix.spark }},jdk-${{ matrix.java }}"
          TEST_MODULES="client-spark/common,client-spark/spark-3,client-spark/spark-3-columnar-common,client-spark/spark-${SPARK_MAJOR_VERSION}-shaded,tests/spark-it"
          build/mvn $PROFILES -pl $TEST_MODULES -am clean install -DskipTests
          build/mvn $PROFILES -pl $TEST_MODULES -Dscalatest.rerunFailingTestsCount=2 -Dsurefire.rerunFailingTestsCount=2 -fae -Dspark.shuffle.sort.io.plugin.class=${{ matrix.shuffle-plugin-class }} test
      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: spark-${{ matrix.spark }}-java-${{ matrix.java }}-unit-test-log
          path: |
            **/target/test-reports/**
            **/target/unit-tests.log
